package com.example.dgscodegeninterfaces

import com.example.dgscodegeninterfaces.generated.client.ProfileGraphQLQuery
import com.example.dgscodegeninterfaces.generated.client.ProfileProjectionRoot
import com.netflix.graphql.dgs.client.codegen.GraphQLQueryRequest

fun main() {
    val projection = ProfileProjectionRoot<Nothing, Nothing>()
        .id()
        .agreements()
        .onPaymentAccount().balance().id().name()
        .parent()
        .onSavingsAccount().balance().id().name()
        .root()

    val query = ProfileGraphQLQuery.Builder().build()
    val request = GraphQLQueryRequest(query, projection)

    println("query: ${request.serialize()}")
    /* prints:
    query: {
      profile {
        id
        agreements {
          ... on PaymentAccount {
            __typename
            balance
            id
            name
          }
          ... on SavingsAccount {
            __typename
            balance
            id
            name
          }
        }
      }
    }
     */

    /* However, this would make a valid query too, but cannot be generated by the codegen tool:
    val projection = ProfileProjectionRoot<Nothing, Nothing>()
    .id()
    .agreements()
    .onAccount().balance().id().name()
    .root()

    query: {
      profile {
        id
        agreements {
          ... on Account {
            __typename
            balance
            id
            name
          }
        }
      }
    }
     */
}
